sudo: false
git:
  depth: 1

language: node_js
node_js:
  - "node"

cache:
  directories:
    - elm/elm-stuff/build-artifacts
    - sysconfcpus

os:
  - linux

env: 
  - ELM_VERSION=0.18.0

before_install:
  - | # epic build time improvement - see https://github.com/elm-lang/elm-compiler/issues/1473#issuecomment-245704142
    if [ ! -d sysconfcpus/bin ];
    then
      git clone https://github.com/obmarg/libsysconfcpus.git;
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    fi
install:
  - node --version
  - npm --version
  - npm install -g elm@$ELM_VERSION webpack@3.11.0 mocha 
  - mv $(npm config get prefix)/bin/elm-make $(npm config get prefix)/bin/elm-make-old
  - echo -e "#\!/bin/bash\\n\\necho \"Running elm-make with sysconfcpus -n 2\"\\n\\n$TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 elm-make-old \"\$@\"" > $(npm config get prefix)/bin/elm-make
  - chmod +x $(npm config get prefix)/bin/elm-make
  - npm install

script:
  - cd elm
  - ../node_modules/elm-test/bin/elm-test
  - cd ..
  - npm test
  - cd elm/src
  - elm-make Demo/Main.elm
  - mv index.html Demo
  - cd ../..

deploy:
  - provider: npm
    email: $EMAIL
    api_key: $NPM_API_KEY
    on:
      branch: master
    tag: latest
    skip_cleanup: true
  - provider: pages
    skip-cleanup: true
    local-dir: elm/src/Demo
    github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    #keep-history: true
    on:
      branch: master